language: python
python:
- '3.6'
env:
  global:
  - BUILD_ON_TRAVIS=true
  - FLANB_OS=linux
  matrix:
  - secure: CALlNlGs7J1jQzUNxkQNBin1Lwpmpf1+KNGtkBOHIj/E+hCrDwbp2rQ7ilr/lfwb7HYlKET5AKJx9YmTn1KrKBzyfLaxx0uoZ8ZirMZmSqTBTA1pBieL1eUq+XBEFmjRqi5PcYrn6J1uRhXsvIWWgzY0ua+N0XSLJVx8raYM8X3RsMvciU7lD3uvsm/7S2GU5ToG57BAA2DZUMhl9P6F2WuXJbB9/UHgam+OEPn/JDS+PDKqucOovHOwsSosqpRMD+zbiHV9eSA4VGpzAN9Q6aGNbnoRLour4NtQAJb/g0/rc2kOmJkfTCElvPYJAdt9hFVk1vlexcuUzYa5CGG2SU5aJ5bFc6G6896BFWZDvuZ67dGNHT7hUQq7V7btq/elvWsenjOaL5On8XRsjbUO8C/2fcO//bY4YIvAs+HQ1avgXfdTsW5wgZBNmn/r6VfHf/E/EUFaUy/EiGgqZmdU5VKDIo4TnhBiQyYOkVMHo5V0/Oj0N8QWUhoj/gjpvNeJz7oSOoplMMweg6BwjUdAjJPQFxr22PtEUTFbDoBpikxL8c6EMqt5B4Dd9bIo9X8uO0EZR4STGZ3hnoDQJj9nuuzWfFzPE5vK80bwd0Ob1QkvI5k5LRNVItFBlSGRyMSxevk/NTviNXYu4p67AH4XKaZWwaQGGmMKtiFBt0l+GAs=
  - secure: 3h9Mnt6syv3PZ0uZdaBEa1kh5s6TMs+V89rK+kWnc6vHvN1jeHbiAJ0fOlwuIQCcCsUnG25yTXH3iYNFwSN2GI8LBOp3y5vjerMoK/Ho1qsKiVcLXYS0IE+qr+/0vWmx0Pf6Nt8Pkf7Zzg3HDYdHLWvOdt08HNYzvRJ1Wd9sqa7zgEvu+ExRL1ARIyazrMpSO9wTopK1zPgHoohN0M3/5x5H95AfJwH09pyU9TdaXLdF36QbSoeJJX3+3+Dellm7CO7PcvyiNogshea6umqP77RIiDuwwoA8VivdvQR1afTRJgBSu77C8rOVHVoBOP8bx073njaakN20QVzW+gVfksaCHsT9Pvcuv/jzVZH/IPi1qIjLn5eAlpM1Druw+sX4VTnpHgZHgBG2Y7kxyZ1Tq5s5VQ2E4bAzGEl5ME/aoMM7YDkzECRWiXe/urtju44qOY9k4z9OGELpbiJayRceRv3EDt93cjpIqxGlnw5JFuhSFYhCs52TOLIsxXdx5DOFc7AjhtODGip9nLg7GjFYDzDlGiRazQQibqvGSQiVKYHQoJScQIisvrrHc0meLElzWt0AosMz9RQDQpjwswPS2yI24kldNsBYZyXD1ZAvCjhOOLOgRvzAZFEaiudx6heV4u5Rh/sU3RKcY6HoGpdcX84ci7I85Nl1OTff2ux/Psg=
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libpq-dev
- sudo apt-get install -y python3-dev
addons:
  chrome: stable
install:
- pip install -r requirements.txt
script:
- python chatbot.py
