
language: python
python:
  - "3.6"

env:
  global:
    - BUILD_ON_TRAVIS=true
    - FLANB_OS=linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpq-dev
  - sudo apt-get install -y python3-dev

addons:
  chrome: stable
  artifacts:
    s3_region: "ap-northeast-2"
    paths:
    - $(ls /tmp/*.png | tr "\n" ":")

install:
  - pip install -r requirements.txt
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - python chatbot.py
