language: python
python:
- '3.6'
env:
  global:
  - BUILD_ON_TRAVIS=true
  - FLANB_OS=linux
  matrix:
  - secure: M1IqoDWkcKIzdIPnA0Rhbe6hiN8lc28DiX0bKKHstaVphXzBYBULIy9G2b2APclPO+Li3mCU/0JwSinbZF4L9sy1NKmvc9nhfnBp0vpbBHjcIHleoNJz2wyLmEB9KyBYmWZ4lqUom8Kzb1ANre7vub5l561RKPjpYov7ja64eRPxfbmjY6/14N3RkpXaAtFuFKfOEJfefQxA3UDu4mTq6gYa8teJ68JxGO3nlyMXxYBXgPKFArgEcJ/vYPy3eNQyHFfzjdjlwIuZNKDsOMdJHjNslvj2AAfoWAxP7enre98yraa34/Dm4PRQOBQ/pkITDxjn5s3wTU9c6CzuF/5EVesfPI0BTPF7ZGBbPOFPLYnhPDhXEMpBkkZ+ui1wutLyuABfx2nlahZi5kTw3OzMkY27zt+vqnZodkMhm2qvYO017ew9ofrZY5hMrWnqz46NUFVxv7tYmVuDEhc7wQY1kYAiQwm3YY3R/6gR5wmocu7W0CFgCcqBpr7tjvQBkCMx4G+cuZAxQonG5o/4dZpCqa2aKOIEQUPBAlNuaPBv+gTVuK/E+yk1fvowH8FSd9W6NywJGoJ1ToF08HemWHgJRbMmfUBz03+UHr3uv9d0uJWcP4AlD2Ysej90Czb0vgvWCNWYMd1dorAQJvrLxTNDikyoJKxrZu1mb1/UzptS3B0=
  - secure: mBw39RZOY5BsfCkjiE3ALgmfHqNnmrvPfFQ2dFxd2dm/HRFd0hD+Cd+vK9oGc/oysjSK/ICY+DF+khP+66prYaNf/d2Sl8CORE8S4KWAMmxCURe4BO+GnM4LEWh+61mSjD+pyoq0vXPl6bzOdXk0vtI9lkm2GIm3PpIRQmHs+5lg30wvOqZDqLWLDRp5KstFvMIFxXi5z6uQBf+cvG8v0J2AVUZZPomvTQ33+VzKKJCN4SbLaxb2rJfweCKzB7YdCaWXW55Ugof5Dg41ybQkyeaK8Gq0j9SGwKeHmB/qSD9jqZ/S3cMq69/Rs+kcfpAZc+zfsEIoFE1Zy9+K6bL4jIWQh/NPAaGHyxGZRlc57RCNuwhvc00Q4drO2DiYF+iI6KU4kO2kk4DUtRiQ7CRCO7jQpGp281SAFdcG8JvpoiQXItmwOMmvdXo/l6y/lcT7bR6GPD+wY2cFtuY5tbS8JlTIfCrGRxaKXH/WAhafZON5Un0dlFXDwpjFpbMfrQv/xveXecMoLPkoobRC7twARmScV/YuSH6F41BfyeZGVXkRLLLoVknA7i3swo+t6ZoNoNZOxO7qZ9hjqWEj50tdjyoUYCGCfkwZR8fgSQpDIPELJ78lL+EpBnE0ujPi7FMINuMUGyYEleJmmpoL4/Ros0gHdHcS9p+5sET7v9GOS+U=
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libpq-dev
- sudo apt-get install -y python3-dev
addons:
  chrome: stable
install:
- pip install -r requirements.txt
script:
- python chatbot.py
